In [2]:
import pandas as pd

In [72]:
df1 =pd.read_csv(r'C:\Users\SRK\Desktop\siva_python\mini_2\fifa.csv')
df2 =pd.read_csv(r'C:\Users\SRK\Desktop\siva_python\mini_2\fifa_+variable_information.csv')

In [5]:
df1.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [12]:
df1.count()

ID                          18207
Name                        18207
Age                         18207
Photo                       18207
Nationality                 18207
Flag                        18207
Overall                     18207
Potential                   18207
Club                        17966
Club Logo                   18207
Value                       18207
Wage                        18207
Preferred Foot              18159
International Reputation    18159
Weak Foot                   18159
Skill Moves                 18159
Work Rate                   18159
Body Type                   18159
Position                    18147
Jersey Number               18147
Joined                      16654
Loaned From                  1264
Contract Valid Until        17918
Height                      18159
Weight                      18159
Crossing                    18159
Finishing                   18159
HeadingAccuracy             18159
ShortPassing                18159
Volleys                     18159
Dribbling                   18159
Curve                       18159
FKAccuracy                  18159
LongPassing                 18159
BallControl                 18159
Acceleration                18159
SprintSpeed                 18159
Agility                     18159
Reactions                   18159
Balance                     18159
ShotPower                   18159
Jumping                     18159
Stamina                     18159
Strength                    18159
LongShots                   18159
Aggression                  18159
Interceptions               18159
Positioning                 18159
Vision                      18159
Penalties                   18159
Composure                   18159
Marking                     18159
StandingTackle              18159
SlidingTackle               18159
GKDiving                    18159
GKHandling                  18159
GKKicking                   18159
GKPositioning               18159
GKReflexes                  18159
Release Clause              16643
dtype: int64

In [7]:
df2.head()

            ID     unique id for every player
0         Name                           name
1          Age                            age
2        Photo      url to the player's photo
3  Nationality                    nationality
4         Flag  url to players's country flag

In [13]:
df1[df1.duplicated()]

Empty DataFrame
Columns: [ID, Name, Age, Photo, Nationality, Flag, Overall, Potential, Club, Club Logo, Value, Wage, Preferred Foot, International Reputation, Weak Foot, Skill Moves, Work Rate, Body Type, Position, Jersey Number, Joined, Loaned From, Contract Valid Until, Height, Weight, Crossing, Finishing, HeadingAccuracy, ShortPassing, Volleys, Dribbling, Curve, FKAccuracy, LongPassing, BallControl, Acceleration, SprintSpeed, Agility, Reactions, Balance, ShotPower, Jumping, Stamina, Strength, LongShots, Aggression, Interceptions, Positioning, Vision, Penalties, Composure, Marking, StandingTackle, SlidingTackle, GKDiving, GKHandling, GKKicking, GKPositioning, GKReflexes, Release Clause]
Index: []

[0 rows x 60 columns]

In [14]:
# there are no duplicates

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 60 columns):
ID                          18207 non-null int64
Name                        18207 non-null object
Age                         18207 non-null int64
Photo                       18207 non-null object
Nationality                 18207 non-null object
Flag                        18207 non-null object
Overall                     18207 non-null int64
Potential                   18207 non-null int64
Club                        17966 non-null object
Club Logo                   18207 non-null object
Value                       18207 non-null object
Wage                        18207 non-null object
Preferred Foot              18159 non-null object
International Reputation    18159 non-null float64
Weak Foot                   18159 non-null float64
Skill Moves                 18159 non-null float64
Work Rate                   18159 non-null object
Body Type                   18159 non-null object
Position                    18147 non-null object
Jersey Number               18147 non-null float64
Joined                      16654 non-null object
Loaned From                 1264 non-null object
Contract Valid Until        17918 non-null object
Height                      18159 non-null object
Weight                      18159 non-null object
Crossing                    18159 non-null float64
Finishing                   18159 non-null float64
HeadingAccuracy             18159 non-null float64
ShortPassing                18159 non-null float64
Volleys                     18159 non-null float64
Dribbling                   18159 non-null float64
Curve                       18159 non-null float64
FKAccuracy                  18159 non-null float64
LongPassing                 18159 non-null float64
BallControl                 18159 non-null float64
Acceleration                18159 non-null float64
SprintSpeed                 18159 non-null float64
Agility                     18159 non-null float64
Reactions                   18159 non-null float64
Balance                     18159 non-null float64
ShotPower                   18159 non-null float64
Jumping                     18159 non-null float64
Stamina                     18159 non-null float64
Strength                    18159 non-null float64
LongShots                   18159 non-null float64
Aggression                  18159 non-null float64
Interceptions               18159 non-null float64
Positioning                 18159 non-null float64
Vision                      18159 non-null float64
Penalties                   18159 non-null float64
Composure                   18159 non-null float64
Marking                     18159 non-null float64
StandingTackle              18159 non-null float64
SlidingTackle               18159 non-null float64
GKDiving                    18159 non-null float64
GKHandling                  18159 non-null float64
GKKicking                   18159 non-null float64
GKPositioning               18159 non-null float64
GKReflexes                  18159 non-null float64
Release Clause              16643 non-null object
dtypes: float64(38), int64(4), object(18)
memory usage: 8.3+ MB

In [29]:
df1.columns[df1.isnull().any()]
# these colmns have null values.

Index(['Club', 'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Position', 'Jersey Number',
       'Joined', 'Loaned From', 'Contract Valid Until', 'Height', 'Weight',
       'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys',
       'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance',
       'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes',
       'Release Clause'],
      dtype='object')

In [64]:
a =df1['Value']
#pattern = 
df1.Value.replace(to_replace=r'\A€',value ='', regex=True,inplace=True)

In [ ]:
df1.Value.replace(to_replace=r'K\b',value ='*(1000)', regex=True,inplace=True)
df1.Value.replace(to_replace=r'M\b',value ='*(1000000)', regex=True,inplace=True)

In [61]:
df1.Value

0        110.5*(1000000)
1           77*(1000000)
2        118.5*(1000000)
3           72*(1000000)
4          102*(1000000)
5           93*(1000000)
6           67*(1000000)
7           80*(1000000)
8           51*(1000000)
9           68*(1000000)
10          77*(1000000)
11        76.5*(1000000)
12          44*(1000000)
13          60*(1000000)
14          63*(1000000)
15          89*(1000000)
16        83.5*(1000000)
17          78*(1000000)
18          58*(1000000)
19        53.5*(1000000)
20        51.5*(1000000)
21          60*(1000000)
22          38*(1000000)
23        64.5*(1000000)
24          27*(1000000)
25          81*(1000000)
26        69.5*(1000000)
27        59.5*(1000000)
28        69.5*(1000000)
29          62*(1000000)
              ...
18177          70*(1000)
18178          50*(1000)
18179          50*(1000)
18180          40*(1000)
18181          50*(1000)
18182          50*(1000)
18183                  0
18184          40*(1000)
18185          50*(1000)
18186          60*(1000)
18187          40*(1000)
18188          60*(1000)
18189          60*(1000)
18190          60*(1000)
18191          50*(1000)
18192          50*(1000)
18193          50*(1000)
18194          50*(1000)
18195          60*(1000)
18196          60*(1000)
18197          60*(1000)
18198          60*(1000)
18199          70*(1000)
18200          60*(1000)
18201          60*(1000)
18202          60*(1000)
18203          60*(1000)
18204          60*(1000)
18205          60*(1000)
18206          60*(1000)
Name: Value, Length: 18207, dtype: object

In [62]:
import numpy as np
df1.Value.astype(np.int16)

ValueError: invalid literal for int() with base 10: '110.5*(1000000)'

In [65]:
 df1.Value.str.extract(r'[\d\.]+([KM]+)', expand=False).replace(['K','M'], [10**3, 10**6]).astype(int)

0        1000000
1        1000000
2        1000000
3        1000000
4        1000000
5        1000000
6        1000000
7        1000000
8        1000000
9        1000000
10       1000000
11       1000000
12       1000000
13       1000000
14       1000000
15       1000000
16       1000000
17       1000000
18       1000000
19       1000000
20       1000000
21       1000000
22       1000000
23       1000000
24       1000000
25       1000000
26       1000000
27       1000000
28       1000000
29       1000000
          ...
18177       1000
18178       1000
18179       1000
18180       1000
18181       1000
18182       1000
18183          1
18184       1000
18185       1000
18186       1000
18187       1000
18188       1000
18189       1000
18190       1000
18191       1000
18192       1000
18193       1000
18194       1000
18195       1000
18196       1000
18197       1000
18198       1000
18199       1000
18200       1000
18201       1000
18202       1000
18203       1000
18204       1000
18205       1000
18206       1000
Name: Value, Length: 18207, dtype: int32

In [71]:
df1.Value = (df1.Value.replace(r'[KM]+$', '', regex=True).astype(float) * \
df1.Value.str.extract(r'[\d\.]+([KM]+)', expand=False).fillna(1).replace(['K','M'], [10**3, 10**6]).astype(int))

SyntaxError: invalid syntax (<ipython-input-71-66cf08525496>, line 2)

In [70]:
df1.Value

0        110500000.0
1         77000000.0
2        118500000.0
3         72000000.0
4        102000000.0
5         93000000.0
6         67000000.0
7         80000000.0
8         51000000.0
9         68000000.0
10        77000000.0
11        76500000.0
12        44000000.0
13        60000000.0
14        63000000.0
15        89000000.0
16        83500000.0
17        78000000.0
18        58000000.0
19        53500000.0
20        51500000.0
21        60000000.0
22        38000000.0
23        64500000.0
24        27000000.0
25        81000000.0
26        69500000.0
27        59500000.0
28        69500000.0
29        62000000.0
            ...
18177        70000.0
18178        50000.0
18179        50000.0
18180        40000.0
18181        50000.0
18182        50000.0
18183            0.0
18184        40000.0
18185        50000.0
18186        60000.0
18187        40000.0
18188        60000.0
18189        60000.0
18190        60000.0
18191        50000.0
18192        50000.0
18193        50000.0
18194        50000.0
18195        60000.0
18196        60000.0
18197        60000.0
18198        60000.0
18199        70000.0
18200        60000.0
18201        60000.0
18202        60000.0
18203        60000.0
18204        60000.0
18205        60000.0
18206        60000.0
Name: Value, Length: 18207, dtype: float64

In [73]:
df1.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Preferred Foot',
       'International Reputation', 'Weak Foot', 'Skill Moves', 'Work Rate',
       'Body Type', 'Position', 'Jersey Number', 'Joined', 'Loaned From',
       'Contract Valid Until', 'Height', 'Weight', 'Crossing', 'Finishing',
       'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve',
       'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')